<?php

namespace Pupilovo\SupplierHub\Infrastructure\Repository;

use Pupilovo\SupplierHub\Infrastructure\Database\Schema;

defined('ABSPATH') || exit;

final class ImportJobRepository {
    public function create_plan(?int $supplier_id,array $context,int $user_id): int {global $wpdb;$now=current_time('mysql',true);$wpdb->insert(Schema::table('jobs'),['uuid'=>wp_generate_uuid4(),'supplier_id'=>$supplier_id,'job_type'=>'import','status'=>'planning','dry_run'=>1,'context'=>wp_json_encode($context),'requested_by'=>$user_id,'created_at'=>$now,'started_at'=>$now,'heartbeat_at'=>$now],null);if(!$wpdb->insert_id)throw new \RuntimeException('Nie udało się utworzyć planu importu.');return(int)$wpdb->insert_id;}
    public function add_item(int $job_id,int $catalog_id,string $action,string $status,array $before,array $after,?string $error=null):void{global $wpdb;$now=current_time('mysql',true);$wpdb->insert(Schema::table('job_items'),['job_id'=>$job_id,'catalog_product_id'=>$catalog_id,'action_type'=>$action,'status'=>$status,'error_code'=>$error,'before_snapshot'=>wp_json_encode($before),'after_snapshot'=>wp_json_encode($after),'created_at'=>$now,'updated_at'=>$now],null);}
    public function finish_plan(int $id,array $summary):void{global $wpdb;$job=$this->get($id);$context=$job['context'];$context['summary']=$summary;$wpdb->update(Schema::table('jobs'),['status'=>'awaiting_approval','total_items'=>array_sum($summary),'context'=>wp_json_encode($context),'finished_at'=>current_time('mysql',true)],['id'=>$id],null,['%d']);}
    public function get(int $id):?array{global $wpdb;$row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Schema::table('jobs').' WHERE id=%d',$id),ARRAY_A);if(!$row)return null;$context=json_decode((string)$row['context'],true);return ['id'=>(int)$row['id'],'uuid'=>$row['uuid'],'supplierId'=>$row['supplier_id']===null?null:(int)$row['supplier_id'],'type'=>$row['job_type'],'status'=>$row['status'],'dryRun'=>(bool)$row['dry_run'],'totalItems'=>(int)$row['total_items'],'processedItems'=>(int)$row['processed_items'],'succeededItems'=>(int)$row['succeeded_items'],'failedItems'=>(int)$row['failed_items'],'context'=>is_array($context)?$context:[],'createdAt'=>$row['created_at'],'finishedAt'=>$row['finished_at']];}
    public function items(int $id):array{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.Schema::table('job_items').' WHERE job_id=%d ORDER BY id',$id),ARRAY_A)?:[];return array_map([$this,'item_record'],$rows);}
    public function ready_items(int $id,int $limit=10):array{global $wpdb;$limit=min(100,max(1,$limit));$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.Schema::table('job_items')." WHERE job_id=%d AND status='ready' ORDER BY id LIMIT %d",$id,$limit),ARRAY_A)?:[];return array_map([$this,'item_record'],$rows);}
    public function count_ready(int $id):int{global $wpdb;return(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.Schema::table('job_items')." WHERE job_id=%d AND status='ready'",$id));}
    public function requeue_failed(int $id,int $max_attempts=3):array{global$wpdb;$max_attempts=max(1,min(10,$max_attempts));$max=(int)$wpdb->get_var($wpdb->prepare('SELECT MAX(attempts) FROM '.Schema::table('job_items')." WHERE job_id=%d AND status='failed' AND attempts<%d",$id,$max_attempts));$count=(int)$wpdb->query($wpdb->prepare('UPDATE '.Schema::table('job_items')." SET status='ready',updated_at=%s WHERE job_id=%d AND status='failed' AND attempts<%d",current_time('mysql',true),$id,$max_attempts));return['count'=>max(0,$count),'delay'=>$count>0?min(3600,60*(2**max(0,$max-1))):0];}
    public function status_counts(int$id):array{global$wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT status,COUNT(*) total FROM '.Schema::table('job_items').' WHERE job_id=%d GROUP BY status',$id),ARRAY_A)?:[];$out=[];foreach($rows as$row)$out[$row['status']]=(int)$row['total'];return$out;}
    public function update_job(int $id,array $data):void{global $wpdb;$wpdb->update(Schema::table('jobs'),$data,['id'=>$id],null,['%d']);}
    public function update_item(int $id,array $data):void{global $wpdb;$data['updated_at']=current_time('mysql',true);$wpdb->update(Schema::table('job_items'),$data,['id'=>$id],null,['%d']);}
    private function item_record(array$row):array{return['id'=>(int)$row['id'],'catalogProductId'=>(int)$row['catalog_product_id'],'action'=>$row['action_type'],'status'=>$row['status'],'wcProductId'=>$row['wc_product_id']?(int)$row['wc_product_id']:null,'attempts'=>(int)$row['attempts'],'errorCode'=>$row['error_code'],'before'=>json_decode((string)$row['before_snapshot'],true)?:[],'after'=>json_decode((string)$row['after_snapshot'],true)?:[]];}
}
